<a href="https://colab.research.google.com/github/schardon/oda-demo-main/blob/main/Cybersecurity_june2024_day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

#Classifying Files by Type


In [10]:
import os
from sklearn.feature_extraction.text import HashingVectorizer, TfidfTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline



In [11]:
javascript_path = "/content/cybersecurity/JavascriptSamples"
python_path = "/content/cybersecurity/PythonSamples"
powershell_path = "/content/cybersecurity/PowerShellSamples"

In [12]:
corpus =[]
labels = []

files_types_and_labels = [(javascript_path, -1), (python_path, 0), (powershell_path, 1)]

for file_path, label in files_types_and_labels:
  files = os.listdir(file_path)
  for file in files:
    file_path = file_path + "/" + file
    try :
      with open(file_path, 'r') as myfile :
        data = myfile.read().replace("\n", "")
    except :
      pass

    data = str(data)
    corpus.append(data)
    labels.append(label)




In [13]:
X_train, X_test, y_train, y_test = train_test_split(corpus, labels, test_size=0.2, random_state=11)

text_clf = Pipeline( [
    ("vect" , HashingVectorizer(input="content", ngram_range=(1, 3))),
    ("tdidf", TfidfTransformer(use_idf=True)),
    ("rf", RandomForestClassifier(class_weight="balanced"))
])


In [14]:
text_clf.fit(X_train, y_train)

Pipeline(steps=[('vect', HashingVectorizer(ngram_range=(1, 3))),
                ('tdidf', TfidfTransformer()),
                ('rf', RandomForestClassifier(class_weight='balanced'))])

In [15]:
y_test_pred = text_clf.predict(X_test)

y_test_pred


array([-1,  0, -1, -1,  1,  0,  0, -1, -1,  0, -1, -1,  0, -1, -1, -1,  0,
        0, -1, -1, -1, -1,  0,  0, -1,  0,  0,  1, -1, -1, -1,  0,  0,  0,
       -1, -1,  0, -1,  0,  0,  0,  1,  0,  0, -1,  0,  0, -1,  0, -1,  0,
       -1, -1, -1,  0, -1,  0, -1,  0,  0,  0,  0,  0,  0,  1, -1,  0, -1,
        0,  1, -1,  0, -1,  0, -1,  0, -1, -1,  0,  0,  0, -1,  0,  0,  1,
        1,  0,  0, -1,  0,  0, -1,  0,  0,  0,  0, -1, -1, -1,  0,  0,  1,
        1,  0, -1,  0, -1, -1, -1, -1,  0,  0,  0, -1,  0, -1, -1, -1, -1,
        0,  0, -1,  1, -1, -1,  0,  1,  0, -1, -1, -1,  1,  1, -1, -1,  0,
       -1,  0,  0, -1, -1, -1,  0,  0,  0,  0,  0,  0, -1, -1,  0,  0, -1,
       -1, -1, -1, -1, -1,  1, -1,  0,  0,  0,  1,  0,  0,  0,  0, -1,  1,
       -1, -1, -1, -1,  0,  1,  0, -1, -1,  0,  1, -1, -1,  0, -1, -1, -1,
       -1, -1,  0,  0, -1,  0,  0, -1, -1,  0,  1,  1,  1,  0, -1,  1, -1,
       -1, -1,  0, -1,  0,  0,  0,  0,  0,  0, -1, -1, -1,  0,  0, -1,  0,
        0, -1,  0, -1,  0

In [18]:
print(accuracy_score(y_test, y_test_pred))

1.0


In [19]:
print(confusion_matrix(y_test, y_test_pred))

[[319   0   0]
 [  0 326   0]
 [  0   0  66]]


# Examining the PE (Portable Executable) Header

In [4]:
! pip install pefile

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.8/71.8 kB 2.4 MB/s eta 0:00:00


In [21]:
import pefile

desired_file = "/content/cybersecurity/HvsiSettingsWorker.exe"

pe = pefile.PE(desired_file)


In [22]:
for entry in pe.DIRECTORY_ENTRY_IMPORT:
  print(entry.dll)
  for imp in entry.imports:
    print("\t", hex(imp.address), imp.name)

b'api-ms-win-crt-runtime-l1-1-0.dll'
	 0x14000a590 b'_initterm'
	 0x14000a598 b'_initterm_e'
	 0x14000a5a0 b'_c_exit'
	 0x14000a5a8 b'_register_thread_local_exe_atexit_callback'
b'api-ms-win-crt-string-l1-1-0.dll'
	 0x14000a5b8 b'memset'
b'api-ms-win-crt-private-l1-1-0.dll'
	 0x14000a468 b'_o__crt_atexit'
	 0x14000a470 b'_o__errno'
	 0x14000a478 b'_o__exit'
	 0x14000a480 b'_o__get_initial_wide_environment'
	 0x14000a488 b'_o__initialize_onexit_table'
	 0x14000a490 b'_o__initialize_wide_environment'
	 0x14000a498 b'_o__invalid_parameter_noinfo'
	 0x14000a4a0 b'_o__invalid_parameter_noinfo_noreturn'
	 0x14000a4a8 b'_o__register_onexit_function'
	 0x14000a4b0 b'_o__seh_filter_exe'
	 0x14000a4b8 b'_o__set_app_type'
	 0x14000a4c0 b'_o__set_fmode'
	 0x14000a4c8 b'_o__set_new_mode'
	 0x14000a4d0 b'memcpy'
	 0x14000a4d8 b'_o__cexit'
	 0x14000a4e0 b'_o__wcsicmp'
	 0x14000a4e8 b'_o__wtoi'
	 0x14000a4f0 b'_o_exit'
	 0x14000a4f8 b'_o_free'
	 0x14000a500 b'_o_malloc'
	 0x14000a508 b'_o_terminate'
	

In [23]:
for section in pe.sections:
  print(section.Name.decode(), section.SizeOfRawData)


.text 35840
.rdata 18432
.data 512
.pdata 2560
.didat 512
.reloc 512


In [24]:
for section in pe.sections:
  print(
      section.name,
      hex(section.VirtualAddress),
      hex(section.Misc_VirtualSize),
      section.SizeOfRawData
  )

IMAGE_SECTION_HEADER 0x1000 0x8bbe 35840
IMAGE_SECTION_HEADER 0xa000 0x47f2 18432
IMAGE_SECTION_HEADER 0xf000 0x958 512
IMAGE_SECTION_HEADER 0x10000 0x888 2560
IMAGE_SECTION_HEADER 0x11000 0x10 512
IMAGE_SECTION_HEADER 0x12000 0x70 512


In [25]:
print(pe.dump_info())

----------DOS_HEADER----------

[IMAGE_DOS_HEADER]
0x0        0x0   e_magic:                       0x5A4D    
0x2        0x2   e_cblp:                        0x90      
0x4        0x4   e_cp:                          0x3       
0x6        0x6   e_crlc:                        0x0       
0x8        0x8   e_cparhdr:                     0x4       
0xA        0xA   e_minalloc:                    0x0       
0xC        0xC   e_maxalloc:                    0xFFFF    
0xE        0xE   e_ss:                          0x0       
0x10       0x10  e_sp:                          0xB8      
0x12       0x12  e_csum:                        0x0       
0x14       0x14  e_ip:                          0x0       
0x16       0x16  e_cs:                          0x0       
0x18       0x18  e_lfarlc:                      0x40      
0x1A       0x1A  e_ovno:                        0x0       
0x1C       0x1C  e_res:                         
0x24       0x24  e_oemid:                       0x0       
0x26       0x26

# Extracting N -Grams from exe file (Can be victim file)

In [27]:
import collections

from nltk import ngrams

file_to_analyze = "/content/cybersecurity/HvsiSettingsWorker.exe"



In [29]:
def read_file(file_path):
  """ Readsin the binary sequence of a binary file """
  with open(file_path, 'rb') as binary_file:
    data = binary_file.read()
  return data


def byte_sequence_to_Ngrams(byte_sequence, N) :
  """ Create a list of N-Grams from a byte sequence """
  return list(ngrams(byte_sequence, N))


def binary_file_to_Ngrams_counts(file, N) :
  """ Takes a binary file and outputs the N-Grams counts of its binary sequence"""
  byte_sequence = read_file(file)
  Ngrams = byte_sequence_to_Ngrams(byte_sequence, N)
  return collections.Counter(Ngrams)



In [30]:
extracted_Ngrams = binary_file_to_Ngrams_counts(file_to_analyze, 4)

In [31]:
extracted_Ngrams

Counter({(77, 90, 144, 0): 1,
         (90, 144, 0, 3): 1,
         (144, 0, 3, 0): 1,
         (0, 3, 0, 0): 17,
         (3, 0, 0, 0): 32,
         (0, 0, 0, 4): 10,
         (0, 0, 4, 0): 9,
         (0, 4, 0, 0): 9,
         (4, 0, 0, 0): 14,
         (0, 0, 0, 255): 44,
         (0, 0, 255, 255): 99,
         (0, 255, 255, 0): 1,
         (255, 255, 0, 0): 29,
         (255, 0, 0, 184): 1,
         (0, 0, 184, 0): 1,
         (0, 184, 0, 0): 1,
         (184, 0, 0, 0): 14,
         (0, 0, 0, 0): 5608,
         (0, 0, 0, 64): 38,
         (0, 0, 64, 0): 38,
         (0, 64, 0, 0): 39,
         (64, 0, 0, 0): 33,
         (0, 0, 0, 248): 9,
         (0, 0, 248, 0): 1,
         (0, 248, 0, 0): 1,
         (248, 0, 0, 0): 6,
         (0, 0, 0, 14): 6,
         (0, 0, 14, 31): 1,
         (0, 14, 31, 186): 1,
         (14, 31, 186, 14): 1,
         (31, 186, 14, 0): 1,
         (186, 14, 0, 180): 1,
         (14, 0, 180, 9): 1,
         (0, 180, 9, 205): 1,
         (180, 9, 205, 33): 

In [32]:
print(extracted_Ngrams.most_common(10))

[((0, 0, 0, 0), 5608), ((204, 204, 204, 204), 246), ((0, 0, 72, 139), 217), ((1, 0, 0, 0), 213), ((0, 0, 0, 72), 156), ((255, 255, 255, 255), 146), ((0, 1, 0, 0), 124), ((0, 0, 1, 0), 118), ((0, 0, 72, 141), 104), ((0, 0, 255, 255), 99)]


# Built a static Malware detector

In [35]:
import os

from os import listdir

directories_with_labels = [("/content/cybersecurity/Benign PE Samples", 0), ("/content/cybersecurity/Malicious PE Samples", 1)]



In [36]:
list_of_samples = []
labels = []

for dataset_path, label in directories_with_labels:
  samples = [ f for f in listdir(dataset_path)]
  for sample in samples :
    file_path = os.path.join(dataset_path, sample)
    list_of_samples.append(file_path)
    labels.append(label)




In [37]:
from sklearn.model_selection import train_test_split

samples_train, samples_test, labels_train, labels_test = train_test_split(list_of_samples, labels, test_size=0.2, random_state=11)




In [38]:
import collections
from nltk import ngrams
import numpy as np
import pefile


def read_file(file_path):
  """ Readsin the binary sequence of a binary file """
  with open(file_path, 'rb') as binary_file:
    data = binary_file.read()
  return data


def byte_sequence_to_Ngrams(byte_sequence, N) :
  """ Create a list of N-Grams from a byte sequence """
  return list(ngrams(byte_sequence, N))


def binary_file_to_Ngrams_counts(file, N) :
  """ Takes a binary file and outputs the N-Grams counts of its binary sequence"""
  byte_sequence = read_file(file)
  Ngrams = byte_sequence_to_Ngrams(byte_sequence, N)
  return collections.Counter(Ngrams)



In [39]:
def get_NGram_features_from_sample(sample, K1_most_frequent_Ngrams_list) :
  """ Takes a sample and produces a feature vector
  The features are the counts of the K1 N - Grams """

  K1 = len(K1_most_frequent_Ngrams_list)
  feature_vector = K1 * [0]
  file_Ngrams = binary_file_to_Ngrams_counts(sample, N)

  for i in range(K1):
      feature_vector[i] = file_Ngrams[K1_most_frequent_Ngrams_list[i]]
  return feature_vector

In [40]:
def preprocess_imports(list_of_DLLs) :
  """ Normalize the naming of the imports of a PE file """
  temp = [x.decode().split(".")[0].lower() for x in list_of_DLLs]
  return " ".join(temp)


In [41]:
def get_imports(pe) :
  """ Get a list of the imports of a PE file """
  list_of_imports = []
  for entry in pe.DIRECTORY_ENTRY_IMPORT:
    list_of_imports.append(entry.dll)
  return preprocess_imports(list_of_imports)

In [42]:
def get_section_names(pe) :
  """ Get a list of the section names of a PE file """
  list_of_section_names = []
  for section in pe.sections:
    for sec in pe.sections :
      normalized_name = sec.Name.decode().replace("\x00", "").lower()
      list_of_section_names.append(normalized_name)
  return "".join(list_of_section_names)

In [43]:
N = 2
Ngram_counts_all = collections.Counter([])
for sample in samples_train:
  Ngram_counts_all += binary_file_to_Ngrams_counts(sample, N)
K1 = 100

K1_most_frequent_Ngrams = Ngram_counts_all.most_common(K1)
K1_most_frequent_Ngrams_list = [x[0] for x in K1_most_frequent_Ngrams]



In [44]:
imports_corpus_train = []
num_sections_train = []
section_names_train = []
Ngram_features_list_train = []
y_train = []

for i in range(len(samples_train)):
  sample = samples_train[i]
  try :
    Ngram_features = get_NGram_features_from_sample(sample, K1_most_frequent_Ngrams_list)

    pe = pefile.PE(sample)
    imports = get_imports(pe)
    n_sections = len(pe.sections)
    sec_names = get_section_names(pe)
    imports_corpus_train.append(imports)
    num_sections_train.append(n_sections)
    section_names_train.append(sec_names)
    Ngram_features_list_train.append(Ngram_features)
    y_train.append(labels_train[i])
  except Exception as e :
    print(sample + ":" + str(e))



/content/cybersecurity/Benign PE Samples/hvsirpcd.exe:'DOS Header magic not found.'
/content/cybersecurity/Benign PE Samples/lpq.exe:'DOS Header magic not found.'
/content/cybersecurity/Malicious PE Samples/cmak.exe:'DOS Header magic not found.'
/content/cybersecurity/Benign PE Samples/InspectVhdDialog.exe:'DOS Header magic not found.'
/content/cybersecurity/Benign PE Samples/iisrstas.exe:'DOS Header magic not found.'
/content/cybersecurity/Benign PE Samples/LxRun.exe:'DOS Header magic not found.'
/content/cybersecurity/Benign PE Samples/InetMgr6.exe:'DOS Header magic not found.'
/content/cybersecurity/Benign PE Samples/iissetup.exe:'DOS Header magic not found.'
/content/cybersecurity/Benign PE Samples/InspectVhdDialog6.3.exe:'DOS Header magic not found.'
/content/cybersecurity/Benign PE Samples/inetinfo.exe:'DOS Header magic not found.'
/content/cybersecurity/Benign PE Samples/InspectVhdDialog6.2.exe:'DOS Header magic not found.'
/content/cybersecurity/Benign PE Samples/LogCollector.e